name: Deploy Github Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: Install NPM package
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Export Next.js app
        run: npm run export

      - name: add nojekyll
        run: touch ./out/.nojekyll

      - name: Deploy to GitHub Pages
        permissions:
          actions: write
          checks: write
          contents: write
          deployments: write
          issues: write
          packages: write
          pull-requests: write
          repository-projects: write
          security-events: write
          statuses: write
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
